# Generated by Django 3.2.13 on 2023-04-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ingedient_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Produkt', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Przepis', max_length=256)),
                ('description', models.TextField(default='krotki opis')),
                ('prep_time', models.SmallIntegerField(null=True)),
                ('cooking_time', models.SmallIntegerField(null=True)),
                ('sum_time', models.SmallIntegerField(null=True)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('portions', models.SmallIntegerField(null=True)),
                ('calories_per_portion', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('carb', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('small_photo', models.ImageField(upload_to='')),
                ('big_photo_1', models.ImageField(upload_to='')),
                ('big_photo_2', models.ImageField(null=True, upload_to='')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ManyToManyField(to='recipe.Category')),
                ('cuisines', models.ManyToManyField(to='recipe.Cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(default='T', max_length=2)),
                ('color', models.CharField(default='#ff5733', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('description', models.TextField(default='Opis kroku')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe.Tag'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Produkt', max_length=128)),
                ('measure', models.CharField(blank=True, choices=[('gr', 'Gramy'), ('ml', 'Mililitry')], default='', max_length=2, null=True)),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingedient_group')),
            ],
        ),
        migrations.AddField(
            model_name='ingedient_group',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
