# Generated by Django 3.2.13 on 2022-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Przepis', max_length=256)),
                ('description', models.TextField(default='krotki opid')),
            ],
        ),
    ]
