# Generated by Django 3.2.13 on 2022-05-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_ingredient_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(choices=[('GR', 'Gramy'), ('ML', 'Mililitry')], default='GR', max_length=2),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='Produkt', max_length=128),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.CharField(default='Opis kroku', max_length=1024),
        ),
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
