# Generated by Django 3.2.13 on 2022-06-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220524_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.ManyToManyField(to='recipe.Cuisine'),
        ),
    ]
