# Generated by Django 3.2.13 on 2022-06-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
            preserve_default=False,
        ),
    ]
