# Generated by Django 3.2.13 on 2022-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20220630_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
