# Generated by Django 3.2.13 on 2022-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20221111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='big_photo_1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='big_photo_2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carb',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='small_photo',
            field=models.ImageField(default=11, upload_to=''),
            preserve_default=False,
        ),
    ]
