# Generated by Django 3.2.13 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20221111_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('gr', 'Gramy'), ('ml', 'Mililitry')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(default='Opis kroku'),
        ),
    ]
